#!/usr/bin/env node
/**
 * FitnessStream SDK — Schema Tool
 *
 * Standalone CLI for endpoint vendors to generate and validate schema files.
 * References the SDK's metric catalog so your schema stays in sync with what
 * the app can actually provide.
 *
 * Usage:
 *   npx fitness-stream-schema generate [--preset running|cycling|gym|all] [-o schema.json]
 *   npx fitness-stream-schema validate <schema.json>
 *   npx fitness-stream-schema list [--source healthkit|computed|location]
 *
 * Or run directly:
 *   node schema-tool.js generate --preset running -o my-schema.json
 *   node schema-tool.js validate my-schema.json
 *   node schema-tool.js list
 */

const fs = require("fs");
const path = require("path");

const catalog = require("./catalog.json");

const allMetrics = [
  ...catalog.metrics.healthkit,
  ...catalog.metrics.computed,
  ...catalog.metrics.location,
];

const allIdentifiers = new Set(allMetrics.map((m) => m.identifier));

// ─── Presets ────────────────────────────────────────────────────────────────

const presets = {
  running: [
    "heart_rate",
    "heart_rate_zone",
    "active_energy_kcal",
    "distance_meters",
    "pace_min_per_km",
    "step_count",
    "running_power",
    "running_speed",
    "latitude",
    "longitude",
    "elevation_meters",
  ],
  cycling: [
    "heart_rate",
    "heart_rate_zone",
    "active_energy_kcal",
    "distance_cycling_meters",
    "cadence",
    "cycling_power",
    "cycling_speed",
    "latitude",
    "longitude",
    "elevation_meters",
  ],
  gym: [
    "heart_rate",
    "heart_rate_zone",
    "active_energy_kcal",
    "step_count",
  ],
  swimming: [
    "heart_rate",
    "heart_rate_zone",
    "active_energy_kcal",
    "distance_swimming",
    "swimming_stroke_count",
  ],
  all: allMetrics.map((m) => m.identifier),
};

// ─── Commands ───────────────────────────────────────────────────────────────

function generate(args) {
  const presetName = getFlag(args, "--preset") || "all";
  const outputPath = getFlag(args, "-o") || getFlag(args, "--output");
  const schemaName =
    getFlag(args, "--name") || `${presetName}-overlay`;

  const identifiers = presets[presetName];
  if (!identifiers) {
    console.error(
      `Unknown preset: "${presetName}". Available: ${Object.keys(presets).join(", ")}`,
    );
    process.exit(1);
  }

  const schema = {
    schema_version: catalog.catalog_version,
    name: schemaName,
    description: `Schema for ${presetName} workout data (generated by fitness-stream-sdk ${catalog.sdk_version})`,
    metrics: identifiers.map((id) => ({
      identifier: id,
      required: false,
    })),
    meta_fields: catalog.meta_fields,
  };

  const json = JSON.stringify(schema, null, 2);

  if (outputPath) {
    fs.writeFileSync(outputPath, json + "\n");
    console.log(`Schema written to ${outputPath}`);
    console.log(`  ${identifiers.length} metrics, preset: ${presetName}`);
  } else {
    console.log(json);
  }
}

function validate(args) {
  const filePath = args[0];
  if (!filePath) {
    console.error("Usage: schema-tool validate <schema.json>");
    process.exit(1);
  }

  let raw;
  try {
    raw = fs.readFileSync(filePath, "utf-8");
  } catch {
    console.error(`Cannot read file: ${filePath}`);
    process.exit(1);
  }

  let schema;
  try {
    schema = JSON.parse(raw);
  } catch {
    console.error(`Invalid JSON in ${filePath}`);
    process.exit(1);
  }

  const errors = [];
  const warnings = [];

  if (!schema.schema_version) {
    errors.push("Missing required field: schema_version");
  }
  if (!schema.name) {
    errors.push("Missing required field: name");
  }
  if (!Array.isArray(schema.metrics) || schema.metrics.length === 0) {
    errors.push("Missing or empty: metrics array");
  }

  const seen = new Set();
  for (const metric of schema.metrics || []) {
    if (!metric.identifier) {
      errors.push("Metric entry missing identifier");
      continue;
    }

    if (seen.has(metric.identifier)) {
      warnings.push(`Duplicate identifier: "${metric.identifier}"`);
    }
    seen.add(metric.identifier);

    if (!allIdentifiers.has(metric.identifier)) {
      const isCustom =
        !catalog.metrics.healthkit.some(
          (m) => m.identifier === metric.identifier,
        ) &&
        !catalog.metrics.computed.some(
          (m) => m.identifier === metric.identifier,
        ) &&
        !catalog.metrics.location.some(
          (m) => m.identifier === metric.identifier,
        );

      if (isCustom) {
        warnings.push(
          `"${metric.identifier}" is not in the SDK catalog — will only resolve if the host app registers it as a custom metric`,
        );
      }
    }

    if (metric.value_type) {
      const validTypes = ["double", "int", "string", "bool", "object"];
      if (!validTypes.includes(metric.value_type)) {
        errors.push(
          `Invalid value_type "${metric.value_type}" for "${metric.identifier}". Valid: ${validTypes.join(", ")}`,
        );
      }
    }
  }

  const DIM = "\x1b[2m";
  const GREEN = "\x1b[32m";
  const YELLOW = "\x1b[33m";
  const RED = "\x1b[31m";
  const RESET = "\x1b[0m";

  console.log(`\nValidating: ${filePath}`);
  console.log(`${DIM}Schema: "${schema.name || "?"}" v${schema.schema_version || "?"}${RESET}`);
  console.log(`${DIM}Metrics: ${schema.metrics?.length || 0}${RESET}\n`);

  if (errors.length === 0 && warnings.length === 0) {
    console.log(`${GREEN}Valid${RESET} — no issues found.\n`);

    const catalogIds = (schema.metrics || [])
      .filter((m) => allIdentifiers.has(m.identifier))
      .map((m) => m.identifier);
    const customIds = (schema.metrics || [])
      .filter((m) => !allIdentifiers.has(m.identifier))
      .map((m) => m.identifier);

    console.log(
      `  Catalog metrics: ${catalogIds.length} (will auto-resolve if app registers them)`,
    );
    if (customIds.length > 0) {
      console.log(
        `  Custom metrics:  ${customIds.length} (require host app registration)`,
      );
    }

    const required = (schema.metrics || []).filter((m) => m.required);
    if (required.length > 0) {
      console.log(
        `  Required:        ${required.length} (schema rejected if any missing)`,
      );
    }
  } else {
    for (const e of errors) {
      console.log(`  ${RED}error${RESET}   ${e}`);
    }
    for (const w of warnings) {
      console.log(`  ${YELLOW}warning${RESET} ${w}`);
    }
  }

  console.log();
  process.exit(errors.length > 0 ? 1 : 0);
}

function list(args) {
  const sourceFilter = getFlag(args, "--source");

  const DIM = "\x1b[2m";
  const CYAN = "\x1b[36m";
  const RESET = "\x1b[0m";

  console.log(
    `\nFitnessStream SDK Metric Catalog — v${catalog.sdk_version}\n`,
  );

  const sources = ["healthkit", "computed", "location"];
  for (const source of sources) {
    if (sourceFilter && sourceFilter !== source) continue;

    const metrics = catalog.metrics[source];
    console.log(`${CYAN}${source}${RESET} ${DIM}(${metrics.length})${RESET}`);

    for (const m of metrics) {
      const unit = m.unit ? ` ${DIM}[${m.unit}]${RESET}` : "";
      const agg = m.aggregation ? ` ${DIM}(${m.aggregation})${RESET}` : "";
      console.log(`  ${m.identifier}${unit}${agg}  → ${m.value_type}`);
    }
    console.log();
  }

  console.log(
    `${DIM}Meta fields (always included): ${catalog.meta_fields.join(", ")}${RESET}`,
  );
  console.log(
    `${DIM}Presets: ${Object.keys(presets).join(", ")}${RESET}\n`,
  );
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function getFlag(args, flag) {
  const idx = args.indexOf(flag);
  if (idx === -1) return null;
  return args[idx + 1] || null;
}

// ─── Main ───────────────────────────────────────────────────────────────────

const [command, ...rest] = process.argv.slice(2);

switch (command) {
  case "generate":
    generate(rest);
    break;
  case "validate":
    validate(rest);
    break;
  case "list":
    list(rest);
    break;
  default:
    console.log(`FitnessStream SDK — Schema Tool v${catalog.sdk_version}`);
    console.log();
    console.log("Commands:");
    console.log(
      "  generate  Create a boilerplate schema from a preset",
    );
    console.log(
      "  validate  Check a schema file against the SDK catalog",
    );
    console.log("  list      Show all available metrics");
    console.log();
    console.log("Examples:");
    console.log(
      "  node schema-tool.js generate --preset running -o schema.json",
    );
    console.log("  node schema-tool.js validate schema.json");
    console.log("  node schema-tool.js list --source healthkit");
    console.log();
    process.exit(command ? 1 : 0);
}
