#!/usr/bin/env node
/**
 * FitnessStream SDK — Schema Tool
 *
 * Standalone CLI for endpoint vendors to generate and validate schema files.
 * References the SDK's metric catalog so your schema stays in sync with what
 * the app can actually provide.
 *
 * Usage:
 *   node schema-tool.js generate [--preset running|cycling|gym|all] [--custom <json|file>] [-o schema.json]
 *   node schema-tool.js validate <schema.json>
 *   node schema-tool.js list [--source healthkit|computed|location]
 *
 * Custom metrics:
 *   node schema-tool.js generate --preset gym --custom '{"current_exercise":"string","weight":"double","sets":"int","reps":"int","current_set":"int"}' -o hybrid.json
 *   node schema-tool.js generate --preset gym --custom custom-metrics.json -o hybrid.json
 */

const fs = require("fs");
const path = require("path");

const catalog = require("./catalog.json");

const allMetrics = [
  ...catalog.metrics.healthkit,
  ...catalog.metrics.computed,
  ...catalog.metrics.location,
];

const allIdentifiers = new Set(allMetrics.map((m) => m.identifier));
const validTypes = ["double", "int", "string", "bool", "object"];

// ─── Presets ────────────────────────────────────────────────────────────────

const presets = {
  running: [
    "heart_rate",
    "heart_rate_zone",
    "active_energy_kcal",
    "distance_meters",
    "pace_min_per_km",
    "step_count",
    "running_power",
    "running_speed",
    "latitude",
    "longitude",
    "elevation_meters",
  ],
  cycling: [
    "heart_rate",
    "heart_rate_zone",
    "active_energy_kcal",
    "distance_cycling_meters",
    "cadence",
    "cycling_power",
    "cycling_speed",
    "latitude",
    "longitude",
    "elevation_meters",
  ],
  gym: [
    "heart_rate",
    "heart_rate_zone",
    "active_energy_kcal",
    "step_count",
  ],
  swimming: [
    "heart_rate",
    "heart_rate_zone",
    "active_energy_kcal",
    "distance_swimming",
    "swimming_stroke_count",
  ],
  all: allMetrics.map((m) => m.identifier),
};

// ─── Custom metric parsing ──────────────────────────────────────────────────

/**
 * Parse a --custom argument which is either:
 *   - Inline JSON: '{"current_exercise":"string","weight":"double"}'
 *   - A path to a JSON file containing the same shape
 *
 * Returns an array of { identifier, value_type } entries.
 */
function parseCustomMetrics(raw) {
  if (!raw) return [];

  let obj;
  if (raw.startsWith("{")) {
    try {
      obj = JSON.parse(raw);
    } catch {
      console.error("Invalid JSON in --custom argument");
      process.exit(1);
    }
  } else {
    try {
      const contents = fs.readFileSync(raw, "utf-8");
      obj = JSON.parse(contents);
    } catch {
      console.error(`Cannot read or parse custom metrics file: ${raw}`);
      process.exit(1);
    }
  }

  const entries = [];
  for (const [key, type] of Object.entries(obj)) {
    if (!validTypes.includes(type)) {
      console.error(
        `Invalid value_type "${type}" for custom metric "${key}". Valid: ${validTypes.join(", ")}`,
      );
      process.exit(1);
    }
    if (allIdentifiers.has(key)) {
      console.error(
        `Custom metric "${key}" conflicts with a catalog metric. Use the catalog identifier directly instead.`,
      );
      process.exit(1);
    }
    entries.push({ identifier: key, value_type: type });
  }
  return entries;
}

// ─── Commands ───────────────────────────────────────────────────────────────

function generate(args) {
  const presetName = getFlag(args, "--preset") || "all";
  const outputPath = getFlag(args, "-o") || getFlag(args, "--output");
  const schemaName = getFlag(args, "--name") || `${presetName}-overlay`;
  const customRaw = getFlag(args, "--custom");
  const customMetrics = parseCustomMetrics(customRaw);

  const identifiers = presets[presetName];
  if (!identifiers) {
    console.error(
      `Unknown preset: "${presetName}". Available: ${Object.keys(presets).join(", ")}`,
    );
    process.exit(1);
  }

  const catalogEntries = identifiers.map((id) => ({
    identifier: id,
    required: false,
  }));

  const customEntries = customMetrics.map((m) => ({
    identifier: m.identifier,
    required: false,
    value_type: m.value_type,
  }));

  const description = customMetrics.length > 0
    ? `Schema for ${presetName} workout data + ${customMetrics.length} custom metrics (generated by fitness-stream-sdk ${catalog.sdk_version})`
    : `Schema for ${presetName} workout data (generated by fitness-stream-sdk ${catalog.sdk_version})`;

  const schema = {
    schema_version: catalog.catalog_version,
    name: schemaName,
    description,
    metrics: [...catalogEntries, ...customEntries],
    meta_fields: catalog.meta_fields,
  };

  const json = JSON.stringify(schema, null, 2);

  if (outputPath) {
    fs.writeFileSync(outputPath, json + "\n");
    console.log(`Schema written to ${outputPath}`);
    console.log(
      `  ${catalogEntries.length} catalog metrics (preset: ${presetName})`,
    );
    if (customMetrics.length > 0) {
      console.log(
        `  ${customMetrics.length} custom metrics (require host app registration)`,
      );
      for (const m of customMetrics) {
        console.log(`    ${m.identifier} → ${m.value_type}`);
      }
    }
  } else {
    console.log(json);
  }
}

function validate(args) {
  const filePath = args[0];
  if (!filePath) {
    console.error("Usage: schema-tool validate <schema.json>");
    process.exit(1);
  }

  let raw;
  try {
    raw = fs.readFileSync(filePath, "utf-8");
  } catch {
    console.error(`Cannot read file: ${filePath}`);
    process.exit(1);
  }

  let schema;
  try {
    schema = JSON.parse(raw);
  } catch {
    console.error(`Invalid JSON in ${filePath}`);
    process.exit(1);
  }

  const errors = [];
  const warnings = [];
  const catalogIds = [];
  const customIds = [];
  const requiredIds = [];

  if (!schema.schema_version) {
    errors.push("Missing required field: schema_version");
  }
  if (!schema.name) {
    errors.push("Missing required field: name");
  }
  if (!Array.isArray(schema.metrics) || schema.metrics.length === 0) {
    errors.push("Missing or empty: metrics array");
  }

  const seen = new Set();
  for (const metric of schema.metrics || []) {
    if (!metric.identifier) {
      errors.push("Metric entry missing identifier");
      continue;
    }

    if (seen.has(metric.identifier)) {
      warnings.push(`Duplicate identifier: "${metric.identifier}"`);
    }
    seen.add(metric.identifier);

    if (metric.value_type && !validTypes.includes(metric.value_type)) {
      errors.push(
        `Invalid value_type "${metric.value_type}" for "${metric.identifier}". Valid: ${validTypes.join(", ")}`,
      );
    }

    if (metric.required) {
      requiredIds.push(metric.identifier);
    }

    if (allIdentifiers.has(metric.identifier)) {
      catalogIds.push(metric.identifier);
    } else {
      customIds.push(metric);
    }
  }

  // Custom metrics without value_type are harder to verify
  for (const m of customIds) {
    if (!m.value_type) {
      warnings.push(
        `Custom metric "${m.identifier}" has no value_type — consider adding one so the app developer can verify the contract`,
      );
    }
  }

  const DIM = "\x1b[2m";
  const GREEN = "\x1b[32m";
  const YELLOW = "\x1b[33m";
  const RED = "\x1b[31m";
  const CYAN = "\x1b[36m";
  const RESET = "\x1b[0m";

  console.log(`\nValidating: ${filePath}`);
  console.log(
    `${DIM}Schema: "${schema.name || "?"}" v${schema.schema_version || "?"}${RESET}`,
  );
  console.log(`${DIM}Metrics: ${schema.metrics?.length || 0}${RESET}\n`);

  if (errors.length > 0) {
    for (const e of errors) {
      console.log(`  ${RED}error${RESET}   ${e}`);
    }
    for (const w of warnings) {
      console.log(`  ${YELLOW}warning${RESET} ${w}`);
    }
    console.log();
    process.exit(1);
  }

  if (warnings.length > 0) {
    for (const w of warnings) {
      console.log(`  ${YELLOW}warning${RESET} ${w}`);
    }
    console.log();
  }

  console.log(
    `${GREEN}Valid${RESET}${warnings.length > 0 ? " (with warnings)" : ""}\n`,
  );

  console.log(
    `  Catalog metrics:  ${catalogIds.length} ${DIM}(auto-resolve if app registers them)${RESET}`,
  );

  if (customIds.length > 0) {
    console.log(
      `  Custom metrics:   ${customIds.length} ${DIM}(require host app registration)${RESET}`,
    );
    for (const m of customIds) {
      const type = m.value_type
        ? ` ${DIM}→ ${m.value_type}${RESET}`
        : ` ${DIM}→ (no type declared)${RESET}`;
      console.log(`    ${CYAN}${m.identifier}${RESET}${type}`);
    }
  }

  if (requiredIds.length > 0) {
    console.log(
      `  Required:         ${requiredIds.length} ${DIM}(schema rejected if any missing)${RESET}`,
    );
  }

  if (customIds.length > 0) {
    console.log(
      `\n  ${DIM}Note: Custom metrics will only resolve if the host app calls${RESET}`,
    );
    console.log(
      `  ${DIM}engine.registerCustom(identifier:valueType:) for each one.${RESET}`,
    );
    console.log(
      `  ${DIM}Verify with the app developer that these are available.${RESET}`,
    );
  }

  console.log();
  process.exit(0);
}

function list(args) {
  const sourceFilter = getFlag(args, "--source");

  const DIM = "\x1b[2m";
  const CYAN = "\x1b[36m";
  const RESET = "\x1b[0m";

  console.log(
    `\nFitnessStream SDK Metric Catalog — v${catalog.sdk_version}\n`,
  );

  const sources = ["healthkit", "computed", "location"];
  for (const source of sources) {
    if (sourceFilter && sourceFilter !== source) continue;

    const metrics = catalog.metrics[source];
    console.log(`${CYAN}${source}${RESET} ${DIM}(${metrics.length})${RESET}`);

    for (const m of metrics) {
      const unit = m.unit ? ` ${DIM}[${m.unit}]${RESET}` : "";
      const agg = m.aggregation ? ` ${DIM}(${m.aggregation})${RESET}` : "";
      console.log(`  ${m.identifier}${unit}${agg}  → ${m.value_type}`);
    }
    console.log();
  }

  console.log(
    `${DIM}Meta fields (always included): ${catalog.meta_fields.join(", ")}${RESET}`,
  );
  console.log(
    `${DIM}Presets: ${Object.keys(presets).join(", ")}${RESET}`,
  );
  console.log(
    `\n${DIM}Custom metrics can be added with --custom during generate:${RESET}`,
  );
  console.log(
    `${DIM}  node schema-tool.js generate --preset gym --custom '{"current_exercise":"string","reps":"int"}' -o schema.json${RESET}\n`,
  );
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function getFlag(args, flag) {
  const idx = args.indexOf(flag);
  if (idx === -1) return null;
  return args[idx + 1] || null;
}

// ─── Main ───────────────────────────────────────────────────────────────────

const [command, ...rest] = process.argv.slice(2);

switch (command) {
  case "generate":
    generate(rest);
    break;
  case "validate":
    validate(rest);
    break;
  case "list":
    list(rest);
    break;
  default:
    console.log(`FitnessStream SDK — Schema Tool v${catalog.sdk_version}`);
    console.log();
    console.log("Commands:");
    console.log(
      "  generate  Create a boilerplate schema from a preset",
    );
    console.log(
      "  validate  Check a schema file against the SDK catalog",
    );
    console.log("  list      Show all available metrics");
    console.log();
    console.log("Examples:");
    console.log(
      "  node schema-tool.js generate --preset running -o schema.json",
    );
    console.log(
      '  node schema-tool.js generate --preset gym --custom \'{"current_exercise":"string","reps":"int"}\' -o hybrid.json',
    );
    console.log(
      "  node schema-tool.js generate --preset gym --custom custom-metrics.json -o hybrid.json",
    );
    console.log("  node schema-tool.js validate schema.json");
    console.log("  node schema-tool.js list --source healthkit");
    console.log();
    process.exit(command ? 1 : 0);
}
